---
- name: Check C:\temp directory exists.
  win_stat:
    path: C:\temp
  register: tempdir

- name: Create C:\temp if it's not existed.
  win_file:
    path: C:\temp
    state: directory
  when: tempdir.stat.exists == False

# - name: Fetch PFX from Nexus.
#   win_get_url:
#     url:  '{{ nexus_url }}'
#     dest: C:\temp\cert.pfx

# comment the win_copy out if nexus or artifactory repo is available to fetch with above module.    
- name: Transfer SSL certificate in PFX format to the target Windows IIS web machine.
  win_copy:
    src: '{{ cert_file }}'
    dest: C:\temp\cert.pfx

- name: Import certificate be used by IIS
  win_certificate_store:
    path: C:\temp\cert.pfx
    file_type: pkcs12
    password: '{{ cert_password }}'
    store_location: LocalMachine
    key_storage: machine
    key_exportable: yes
    state: present
  become: True
  become_method: runas
  become_user: SYSTEM
  register: cert_import
  when: not ansible_check_mode

# - name: Repair import cert in case private key is missing.
#   win_command: 'certutil -repairstore my "{{cert_import.thumbprints[0]}}"'
#   become: True
#   become_method: runas
#   become_user: SYSTEM

- name: Add a HTTPS binding with host header and SNI enabled
  win_iis_webbinding:
    name: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    certificate_hash: '{{ cert_import.thumbprints[0] }}'
    port: '{{ item.port }}'
    ip: '{{ item.ip }}'    
    host_header: '{{ item.host }}'    
    state: present
    ssl_flags: 0
    #require_sni: true           # Enables for multiple websites with port 443 on different DNS names and IPs. Tries ssl_flags: true
  loop: '{{ uk1_app_website }}'
  when: not ansible_check_mode

# The ssl_flags: 1 will check/tick the Require Server Name Indication, but has a warning message as follows
# No default SSL site has been created. To support browsers without any SNI capabilities, it is recommended to create default SSL site
#
# The C:\Windows\System32\inetsrv\Config\applicationHost.config should holds all the websites with ssFlags="0"
#
# ssl_flags: 0  = to disable SNI and 1 = to enabled SNI
#
# Require Server Name Binding is require when you have SSL sharing the same DNS, IP and port on multiple websites in which you shouldn't consider.