---
# This will install all Web-Server sub-components and some of them are vulnerable and not needed.
# - name: Install IIS Web-Server with sub features and management tools
#   win_feature:
#     name: Web-Server
#     state: present
#     restart: True
#     include_sub_features: True
#     include_management_tools: True

# Do not add include_include_sub_features: true 
# This might install all roles and features which may cause a Windows security vulnerable and heavy performance load.
- name: Install Windows Roles and Features.
  win_feature:
    name: "{{ win_role_features }}"
    state: present
    include_management_tools: true

# With WINRM. This module is not working with error "msg": "specified folder must already exist: path"
# Also applied to win_iis_virtualdirectory
# - name: Add ACME webapplication on IIS.
#   win_iis_webapplication:
#     name: api
#     site: acme
#     state: present
#     physical_path: C:\inetpub\wwwroot\api
#   #with_items: "{{ users_with_items }}"
#   when: not ansible_check_mode

- name: Create website physical path.
  win_file:
    path: "{{ unc_host }}\\{{ item.name }}"
    state: directory
  with_items: "{{ uk1_app_website }}"
 
- name: Create a New Website.
  win_iis_website:
    name: "{{ item.name }}"
    state: started
    ip: "{{ item.ip }}"
    #port: "{{ item.port }}"
    hostname: "{{ item.host }}"
    application_pool: DefaultAppPool # Ansible can accept DefaultAppPool only.
    physical_path: "C:\\inetpub\\wwwroot\\{{ item.name }}"
    parameters: logfile.directory:C:\inetpub\logs
  with_items: "{{ uk1_app_website }}"
  when: not ansible_check_mode