---
- name: Check C:\temp directory exists.
  win_stat:
    path: C:\temp
  register: tempdir

- name: Create C:\temp if it's not existed.
  win_file:
    path: C:\temp
    state: directory
  when: tempdir.stat.exists == False

# - name: Fetch PFX from Nexus.
#   win_get_url:
#     url:  '{{ nexus_url }}'
#     dest: C:\temp\cert.pfx
    
- name: Transfer SSL certificate in PFX format to the target Windows IIS web machine.
  win_copy:
    src: '{{ cert_file }}'
    dest: C:\temp\cert.pfx

- name: Import certificate be used by IIS
  win_certificate_store:
    path: C:\temp\cert.pfx
    file_type: pkcs12
    password: '{{ cert_password }}'
    store_location: LocalMachine
    key_storage: machine
    key_exportable: yes
    state: present
  become: True
  become_method: runas
  become_user: SYSTEM
  register: cert_import
  when: not ansible_check_mode

# - name: Repair import cert in case private key is missing.
#   win_command: 'certutil -repairstore my "{{cert_import.thumbprints[0]}}"'
#   become: True
#   become_method: runas
#   become_user: SYSTEM

- name: Add a HTTPS binding with host header and SNI enabled
  win_iis_webbinding:
    name: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    certificate_hash: '{{ cert_import.thumbprints[0] }}'
    port: '{{ item.port }}'
    ip: '{{ item.ip }}'    
    host_header: '{{ item.host }}'    
    state: present
  loop: '{{ uk1_app_website }}'
  when: not ansible_check_mode